import {
  SkinProfileAccessActorType,
  SkinProfileAccessEventType,
  SkinProfileAccessPurpose,
  SkinProfileConsentType,
  type SkinProfile,
  type SkinProfileAccessLog,
  type SkinProfileOptions,
} from "@/types/skin-profile";

export const mockSkinProfileOptions: SkinProfileOptions = {
  skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
  skinTones: [
    "very_light",
    "light",
    "light_medium",
    "medium",
    "medium_dark",
    "dark",
    "very_dark",
  ],
  ethnicities: [
    "black",
    "white_caucasian",
    "asian",
    "hispanic_latino",
    "middle_eastern",
    "mixed",
    "other",
  ],
  concerns: [
    "acne",
    "dark_marks",
    "dryness",
    "oiliness",
    "texture",
    "redness",
    "large_pores",
    "fine_lines",
    "barrier_damage",
    "eczema",
    "uneven_tone",
  ],
  fitzpatrickPhototypes: ["I", "II", "III", "IV", "V", "VI"],
  sensitivityLevels: ["low", "moderate_level", "high", "very_high"],
  hydrationLevels: ["well_hydrated", "dehydrated", "very_dehydrated"],
  pregnancyStatuses: [
    "not_pregnant",
    "trying_to_conceive",
    "pregnant",
    "breastfeeding",
    "prefer_not_to_say",
  ],
  sexAtBirth: ["female", "male", "intersex", "prefer_not_to_say"],
  conditions: [
    "rosacea",
    "eczema",
    "psoriasis",
    "perioral_dermatitis",
    "seborrheic_dermatitis",
    "melasma",
    "vitiligo",
    "keratosis_pilaris",
    "other",
  ],
  medications: [
    "isotretinoin",
    "topical_retinoid",
    "topical_antibiotic",
    "oral_antibiotic",
    "hormonal_contraceptive",
    "hrt",
    "topical_corticosteroid",
    "other_photosensitizing",
  ],
  procedureTypes: [
    "chemical_peel",
    "laser",
    "microneedling",
    "microdermabrasion",
    "botox",
    "filler",
  ],
  sunscreenHabits: ["rarely", "when_outside", "most_days", "every_day"],
  sunscreenTolerances: [
    "fine",
    "a_bit_irritating",
    "often_irritating",
    "havent_tried_many",
  ],
  sunscreenFilters: ["chemical", "mineral", "hybrid"],
  sunscreenFinishes: ["matte", "dewy", "tinted", "natural"],
  tendencyLevels: ["never", "sometimes", "often", "always"],
  activeIngredients: [
    "retinoids",
    "aha",
    "bha",
    "pha",
    "benzoyl_peroxide",
    "vitamin_c",
    "niacinamide",
    "azelaic_acid",
    "exfoliation",
  ],
  activeToleranceLevels: [
    "never_tried",
    "tolerates_well",
    "sensitive_to_it",
    "cannot_use",
  ],
  routinePaces: ["cautious", "moderate", "aggressive"],
  budgetTiers: ["drugstore", "mid", "premium", "luxury"],
  texturePreferences: ["lightweight", "rich", "gel", "cream", "oil_free"],
  ingredientEthics: ["vegan", "cruelty_free", "fragrance_free", "clean"],
  reactionTriggerTypes: [
    "ingredient",
    "product",
    "category",
    "fragrance",
    "preservative",
  ],
  reactionTypes: [
    "redness",
    "itch",
    "stinging",
    "dryness",
    "breakout",
    "hives",
    "swelling",
  ],
  reactionSeverities: ["mild", "moderate", "severe"],
  reactionCertainties: [
    "suspected",
    "confirmed_repeat",
    "confirmed_patch_test",
  ],
  sleepLevels: ["under_6", "6_to_8", "over_8"],
  stressLevels: ["low", "moderate", "high"],
  waterIntakeLevels: ["low", "moderate", "high"],
  waterHardnessLevels: ["unknown", "soft", "moderate", "hard"],
  waterSensitivityLevels: ["none", "suspected", "confirmed"],
  dietFlags: [
    "high_sugar",
    "high_dairy",
    "low_sugar",
    "low_dairy",
    "vegan",
    "vegetarian",
  ],
  smokingLevels: ["none", "occasional", "regular"],
  alcoholLevels: ["none", "occasional", "regular"],
  climateSensitivities: ["dry_air", "humidity", "cold", "pollution", "heat"],
  cyclePatterns: ["regular", "irregular", "not_applicable", "not_sure"],
  hormonalBreakoutPatterns: [
    "before_period",
    "during_period",
    "ovulation",
    "random",
    "not_sure",
  ],
};

export const mockSkinProfile: SkinProfile = {
  id: "profile-1",
  dateOfBirth: "1992-04-15",
  sexAtBirth: "female",
  skinType: "oily",
  skinTone: "medium",
  ethnicity: "black",
  currentConcerns: ["acne"],
  countryCode: null,
  city: null,
  fitzpatrickPhototype: "IV",
  sensitivityLevel: null,
  hydrationLevel: null,
  primaryGoal: "acne",
  pregnancyStatus: null,
  underDermatologistCare: null,
  allowSmartPicks: true,
  budgetTier: "mid",
  safetyContext: {},
  reactionHistory: {},
  concernDetails: {
    per_concern: [
      {
        concern: "acne",
        severity: "moderate",
        priority: 1,
      },
    ],
  },
  skinBehavior: {
    burn_tendency: "sometimes",
    pih_tendency: "often",
    melasma_tendency: "never",
    keloid_tendency: "never",
    sunscreen_habit: "most_days",
    sunscreen_tolerance: "fine",
  },
  activeTolerances: {},
  routinePreferences: {
    pace: "cautious",
    am_minutes: 5,
    pm_minutes: 10,
    max_active_nights_per_week: 3,
    fragrance_free: true,
    non_comedogenic: true,
    sunscreen_filter: "hybrid",
    sunscreen_finish: "natural",
  },
  lifestyleContext: {
    water_hardness: "unknown",
    water_sensitivity: "none",
  },
  shoppingPreferences: {},
  hormonalContext: {},
  completeness: 65,
  hasHealthContextConsent: false,
  hasLocationContextConsent: false,
  hasHormonalContextConsent: false,
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
};

export const mockSkinProfileAccessLogs: SkinProfileAccessLog[] = [
  {
    id: "access-log-1",
    consentType: SkinProfileConsentType.HealthContextProcessing,
    eventType: SkinProfileAccessEventType.DataAccessed,
    actorType: SkinProfileAccessActorType.User,
    purpose: SkinProfileAccessPurpose.SkinProfileRead,
    createdAt: "2024-01-02T00:00:00.000Z",
  },
];
