export enum AppRoute {
  Home = '/',
  Features = '/features',
  HowItWorks = '/how-it-works',
  SkinJournalMarketing = '/skin-journal',
  SmartRoutine = '/smart-routine',
  ProductCheckerMarketing = '/product-checker',
  Login = '/login',
  Register = '/register',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password',
  VerifyEmail = '/verify-email',
  ConfirmAccountDeletion = '/confirm-account-deletion',
  CancelAccountDeletion = '/cancel-account-deletion',
  ResendVerification = '/resend-verification',
  PostLogin = '/post-login',
  Dashboard = '/dashboard',
  CheckProduct = '/check-product',
  SkinProfile = '/skin-profile',
  Shelf = '/shelf',
  TodaysSuggestion = '/todays-suggestion',
  Schedule = '/routine',
  Journal = '/journal',
  SmartPicks = '/smart-picks',
  SmartPicksWishlist = '/smart-picks/wishlist',
  Community = '/community',
  History = '/history',
  Insights = '/insights',
  Notifications = '/notifications',
  Settings = '/settings',
  Privacy = '/privacy',
  Terms = '/terms',
}

export const NOTIFICATION_SETTINGS_ROUTE = `${AppRoute.Settings}?tab=notifications`;

export const PROTECTED_APP_ROUTES = [
  AppRoute.PostLogin,
  AppRoute.Dashboard,
  AppRoute.CheckProduct,
  AppRoute.SkinProfile,
  AppRoute.Shelf,
  AppRoute.TodaysSuggestion,
  AppRoute.Schedule,
  AppRoute.Journal,
  AppRoute.SmartPicks,
  AppRoute.SmartPicksWishlist,
  AppRoute.Community,
  AppRoute.History,
  AppRoute.Insights,
  AppRoute.Notifications,
  AppRoute.Settings,
] as const;

export const PUBLIC_METADATA_ROUTES = [
  AppRoute.Home,
  AppRoute.Features,
  AppRoute.HowItWorks,
  AppRoute.SkinJournalMarketing,
  AppRoute.SmartRoutine,
  AppRoute.ProductCheckerMarketing,
  AppRoute.Privacy,
  AppRoute.Terms,
] as const;
